[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
readme = "README.md"
requires-python = ">=3.12"
name = "lightning_tune"
version = "2026.2"
description = "A production-ready library for automated, advanced multi-modal LLM finetuning and deployment."
authors = [
    {name = "Jules", email = "jules@example.com"},
]
license = {text = "Apache-2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "polars[pyarrow]>=0.20.0",
    "litgpt",
    "lightning[all]",
    "litserve",
    "mlflow",
    "pynvml",
    "gradio",
    "streamlit",
    "optuna",
    "typer",
    "evaluate",
    "pyyaml",
    "pydantic",
    "timm",
    "scikit-learn",
    "Pillow",
    "torchmetrics",
    "tensorboard",
    "torchvision",
    "transformers",
    "peft",
    "trl",
    "accelerate",
    "bitsandbytes",
    "datasets",
    "fastapi",
    "uvicorn[standard]",
    "huggingface_hub",
    "python-multipart",
    "torchcodec",
    "ffmpeg",
    "soundfile>=0.13.1",
    "torchaudio>=2.10.0",
    "torch>=2.10.0",
    "twine>=6.2.0",
    "build>=1.4.0",
]

[project.optional-dependencies]
test = ["pytest", "httpx"]
build = ["build"]

[tool.setuptools.packages.find]
where = ["src"]
